ArabWorldMap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizzes.urls', namespace='quizzes')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

quizzes/urls.py
from django.urls import path
from .views import (
    home,
    register,
    login_user,
    logout_user,
    progress_view,
    quiz_view,
    quiz_data_view,
    submit_quiz_view,
    phase2_view,
    phase2_data_view,
    submit_phase2_view
    )

app_name = 'quizzes'

urlpatterns = [
    path('', home, name='home'),
    path('register', register, name='register'),
    path('login_user', login_user, name='login_user'),
    path('logout_user', logout_user, name='logout_user'),
    path('home', home, name='home'),
    path('<str:countryName>/progress/', progress_view, name='main-view'),
    path('<str:countryName>/progress/<int:pk>/', quiz_view, name='quiz-view'),
    path('<str:countryName>/progress/<int:pk>/submit/', submit_quiz_view, name='submit-view'),
    path('<str:countryName>/progress/<int:pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('<str:countryName>/progress/<int:pk>/phase2/', phase2_view, name='phase2-view'),
    path('<str:countryName>/progress/<int:pk>/phase2/submit/', submit_phase2_view, name='submit-phase2-view'),
    path('<str:countryName>/progress/<int:pk>/phase2/data/', phase2_data_view, name='phase2-data-view'),

]

quizzes/models.py
from django.db import models
from random import random

# Create your models here.
class Country(models.Model):
    name = models.CharField(max_length=50, null=True)

    def __str__(self):
        return f"{self.name}"

    def get_quizzes(self):
        return self.quiz_set.all()

    class Meta:
        verbose_name_plural = 'Countries'


class Phase1Quiz(models.Model):
    name = models.CharField(max_length=120, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    # country = models.CharField(max_length=50, null=True)
    required_score_to_pass = models.IntegerField(help_text="required score to pass", null=True)

    def __str__(self):
        return f"{self.name}"

    def get_questions(self):
        return self.phase1question_set.all()

    class Meta:
        verbose_name_plural = 'Phase 1 Quizzes'

class Phase1Question(models.Model):
    text = models.CharField(max_length=200, null=True)
    quiz = models.ForeignKey(Phase1Quiz, on_delete=models.CASCADE, null=True)
    op1 = models.CharField(max_length=200, null=True)
    op2 = models.CharField(max_length=200, null=True)
    op3 = models.CharField(max_length=200, null=True)
    op4 = models.CharField(max_length=200, null=True)
    answer = models.CharField(max_length=200, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answer(self):
        return self.answer

    class Meta:
        verbose_name_plural = 'Phase 1 Questions'


class Phase2Quiz(models.Model):
    name = models.CharField(max_length=120, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    required_score_to_pass = models.IntegerField(help_text="required score to pass", null=True)

    def __str__(self):
        return f"{self.name}"

    def get_questions(self):
        return self.phase2question_set.all()

    class Meta:
        verbose_name_plural = 'Phase 2 Quizzes'

class Phase2Question(models.Model):
    text = models.CharField(max_length=200, null=True)
    quiz = models.ForeignKey(Phase2Quiz, on_delete=models.CASCADE, null=True)
    answer = models.CharField(max_length=200, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answer(self):
        return self.answer

    class Meta:
        verbose_name_plural = 'Phase 2 Questions'


class Phase3Quiz(models.Model):
    name = models.CharField(max_length=120, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    required_score_to_pass = models.IntegerField(help_text="required score to pass", null=True)

    def __str__(self):
        return f"{self.name}"

    def get_questions(self):
        return self.phase3question_set.all()

    class Meta:
        verbose_name_plural = 'Phase 3 Quizzes'

class Phase3Question(models.Model):
    text = models.CharField(max_length=200, null=True)
    quiz = models.ForeignKey(Phase3Quiz, on_delete=models.CASCADE, null=True)
    answer = models.CharField(max_length=200, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answer(self):
        return self.answer

    class Meta:
        verbose_name_plural = 'Phase 3 Questions'

quizzes/views.py
from django.shortcuts import render, redirect
from .models import Phase1Quiz, Phase1Question, Phase2Quiz, Phase2Question, Phase3Quiz, Phase3Question, Country
from django.views.generic import ListView
from django.http import JsonResponse
from results.models import Result
from django.core import serializers
import json

from django.contrib import messages
from django.contrib.auth.models import User, auth

# Create your views here.

def home(request):

    countries = Country.objects.all()
    context = {'countries': countries}
    return render(request, 'quizzes/home.html', context)


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username is already taken')
                return redirect(register)
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email is already taken')
                return redirect(register)
            else:
                user = User.objects.create_user(username=username, password=password,
                                                email=email, first_name=first_name, last_name=last_name)
                user.save()

                return redirect('quizzes/login_user')


        else:
            messages.info(request, 'Both passwords are not matching')
            return redirect(register)


    else:
        return render(request, 'quizzes/registration.html')



def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Invalid Username or Password')
            return redirect('quizzes/login_user')

    else:
        return render(request, 'quizzes/login.html')


def logout_user(request):
    auth.logout(request)
    return redirect('/')

# class Country(ListView):
#     model = Country
#     template_name = 'quizzes/main.html'

# class Progress(ListView):
#     model = Quiz
#     template_name = 'quizzes/main.html'
#
#     def get_results(self, request):
#         result = Result.objects.get(quiz=Quiz.name)
#
#         print('result in get_results: ', result)
#         context = {'result': result}
#         return render(request, self.template_name, context)

def progress_view(request, countryName):
    # Filter through country list to get the country name and then
    # country = Country.objects.get(name=countryName)

    country = Country.objects.get(name=countryName)
    countryName = country.name
    prequiz = Phase1Quiz.objects.filter(name__contains='Pre-Quiz')
    phase1 = Phase1Quiz.objects.filter(name__contains='Phase 1')
    phase2 = Phase2Quiz.objects.filter(name__contains='Phase 2')
    phase3 = Phase3Quiz.objects.filter(name__contains='Phase 3')
    print('Quizzes: ', prequiz, phase1, phase2, phase3)
    results = serializers.serialize("json", Result.objects.filter(country=country))
    results = json.loads(results)
    print('Results: ', results)

    context = {'prequiz': prequiz,
               'phase1': phase1,
               'phase2': phase2,
               'phase3': phase3,
               'results': results,
               'countryName': countryName}
    # prequiz = Quiz.objects.get(country=country, pk=1)
    # prequiz_result = Result.objects.filter(quiz=prequiz).order_by('-score').first()
    #
    # loc_quiz_1 = Quiz.objects.get(pk=2)
    # loc_quiz_result_1 = Result.objects.filter(quiz=loc_quiz_1).order_by('-score').first()
    #
    # cult_quiz_1 = Quiz.objects.get(pk=3)
    # cult_quiz_result_1 = Result.objects.filter(quiz=cult_quiz_1).order_by('-score').first()
    #
    # lang_quiz_1 = Quiz.objects.get(pk=4)
    # lang_quiz_result_1 = Result.objects.filter(quiz=lang_quiz_1).order_by('-score').first()
    #
    # pop_quiz_1 = Quiz.objects.get(pk=5)
    # pop_quiz_result_1 = Result.objects.filter(quiz=pop_quiz_1).order_by('-score').first()
    #
    # hist_quiz_1 = Quiz.objects.get(pk=6)
    # hist_quiz_result_1 = Result.objects.filter(quiz=hist_quiz_1).order_by('-score').first()
    #
    # context = {'prequiz': prequiz,
    #            'prequiz_result': prequiz_result,
    #
    #            'loc_quiz_1': loc_quiz_1,
    #            'loc_quiz_result_1': loc_quiz_result_1,
    #
    #            'cult_quiz_1': cult_quiz_1,
    #            'cult_quiz_result_1': cult_quiz_result_1,
    #
    #            'lang_quiz_1': lang_quiz_1,
    #            'lang_quiz_result_1': lang_quiz_result_1,
    #
    #            'pop_quiz_1': pop_quiz_1,
    #            'pop_quiz_result_1': pop_quiz_result_1,
    #
    #            'hist_quiz_1': hist_quiz_1,
    #            'hist_quiz_result_1': hist_quiz_result_1
    #            }

    return render(request, 'quizzes/main.html', context)

def quiz_view(request, countryName, pk):
    country = Country.objects.get(name=countryName)

    phase1quizzes = Phase1Quiz.objects.get(country=country, pk=pk)
    # phase2quizzes = Phase2Quiz.objects.get(country=country, pk=pk)
    # phase3quizzes = Phase3Quiz.objects.get(country=country, pk=pk)

    print('Country: ', country)
    context = {'phase1': phase1quizzes,
               # 'phase2': phase2quizzes,
               # 'phase3': phase3quizzes,
               'historical_image1': 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Cirene_-_il_teatro_-_panoramio.jpg',
               'historical_image2': 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Cirene_-_il_teatro_-_panoramio.jpg',
               'historical_image3': 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Cirene_-_il_teatro_-_panoramio.jpg',
               'image1_desc': 'Leptis Magna Theatre',
               'image2_desc': 'Ruins of Cyrene',
               'image3_desc': 'Arc of Marcus Aurelius',
               'video': 'https://www.youtube.com/embed/SNTtyIEDrfk'
               }
    # {'country': country,

    return render(request, 'quizzes/quiz.html', context)

def quiz_data_view(request, countryName, pk):
    country = Country.objects.get(name=countryName)
    quiz = Phase1Quiz.objects.get(country=country, pk=pk)

    questions = []
    for q in quiz.get_questions():
        answers = []
        answers.append(q.op1)
        answers.append(q.op2)
        answers.append(q.op3)
        answers.append(q.op4)
        questions.append({str(q): answers})

    return JsonResponse({
        'data': questions,
        'answer': q.answer
    })

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def submit_quiz_view(request, countryName, pk):
    # print(request.POST)
    if is_ajax(request):
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Phase1Question.objects.get(text=k, quiz=pk)
            questions.append(question)

        print(questions)

        country = Country.objects.get(name=countryName)
        user = request.user
        quiz = Phase1Quiz.objects.get(country=country, pk=pk)

        score = 0
        numQuestions = 0
        results = []
        correct_answer = None

        for q in questions:
            numQuestions += 1
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                if a_selected == q.answer:
                    score += 1
                    correct_answer = q.answer
                else:
                    correct_answer = q.answer

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})

            else:
                results.append({str(q): 'not answered'})

        multiplier = 100 / numQuestions
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, country=country, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})



def phase2_view(request, countryName, pk):
    country = Country.objects.get(name=countryName)

    quiz = Phase2Quiz.objects.get(country=country, pk=pk)

    context = {'obj': quiz}

    return render(request, 'quizzes/phase2.html', context)


def phase2_data_view(request, countryName, pk):
    country = Country.objects.get(name=countryName)
    quiz = Phase2Quiz.objects.get(country=country, pk=pk)

    questions = []
    for q in quiz.get_questions():
        questions.append({str(q): q.answer})

    return JsonResponse({
        'data': questions,
    })


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def submit_phase2_view(request, countryName, pk):
    # print(request.POST)
    if is_ajax(request):
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')
        print('Data: ', data_)


        for k in data_.keys():
            print('key: ', k)
            question = Phase2Question.objects.get(text=k)
            questions.append(question)

        print(questions)

        country = Country.objects.get(name=countryName)
        user = request.user
        quiz = Phase2Quiz.objects.get(country=country, pk=pk)

        score = 0
        numQuestions = 0
        results = []
        correct_answer = None

quizzes/templates/quizzes/home.html
{% extends "base.html" %}

{% block title %}
    Home
{% endblock title %}

{% block left-btn %}
    <h6>Welcome, {{ request.user.username }}</h6>
    <a href="{% url 'quizzes:logout_user' %}">Logout</a>
{% endblock left-btn %}

{%  block content %}
    <br>
    <br>
    <h2 style="font-family:arial";><center>Welcome to</center></h2>
    <h1 style="font-family:arial; color:MediumSeaGreen";><center>Talking Arab World Map</center></h1>
    <br>
    <br>

    <img src="https://upload.wikimedia.org/wikipedia/commons/f/f3/A_map_of_the_Arab_World_with_flags.svg"
         alt="Talking Arab World Map"
         style="width:50%; height:50%"
         class="center">

    {% for country in countries %}
    <a href="{% url 'quizzes:main-view' country.name %}">
        <button id = startBtn class="btn btn-link btn-sm"
            data-pk="{{ country.pk }}"
            data-country="{{ country.name }}">{{ country.name }}
        </button>
    </a>
    {% endfor %}

    <br>
    <br>
    <p style="font-size:30px"><center>Click on an Arab Country to learn more about its cultural and historic background.</center>
{% endblock content %}

quizzes/templates/quizzes/instructions_modal.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<!-- The Modal -->
<div id="instructionsModal" class="instructions-modal">

    <!-- Modal content -->
    <div class="instructions-modal-content">
        <span class="instructions-close">&times;</span>
        <h3 style=color:mediumSeaGreen>Overview</h3>
        <p style=font-size:11px>Talking Arab World Map focuses on not only improving students' Arabic language skills,
        but it also improves their knowledge on the culture and history of the 22 Arab countries.
        Students are able to select an Arab country from the world map. For each country, students
        can take a pre-assessment quiz and work through three learning phases as they improve. The
        first phase focuses on audio comprehension, the second phase focuses on conversations,
        and the third phase focuses on speaking & writing. Within each phase, students will learn
        and be tested on 5 categories: Location, Culture-Politics, Language-Religion, Population,
        and History-Economy. The three phases will take approximately 50 hours in order to achieve
        a 100% final score.</p>

        <h3 style=color:mediumSeaGreen>Phase 1</h3>
        <p style="font-size:11px">The student will watch a 1-3 minute video on the first category and
        then take a 5 question quiz about the video. If the student reaches a perfect score on the quiz,
        the student will be allowed to move on to the next category. The process wll repeat until the student
        has completed all 5 categories. After completing the categories, the student will be permitted to
        move on to Phase 2.</p>

        <h3 style=color:mediumSeaGreen>Phase 2</h3>
        <p style="font-size:11px">The student will read a short text about the first category and then
        have a conversation with a Western student about the text. Students will read a question posed by the
        Western student and will then be prompted to input a response. The audio output of the student's
        response will play. Students will continue to converse with the student until that category is complete.
        Once the student completes the conversation, the student will be allowed to move on to the next
        category. This process will repeat until the student has completed all 5 categories. After
        completing the categories, the student will be permitted to move on to Phase 3.</p>

        <h3 style=color:mediumSeaGreen>Phase 3</h3>
        <p style="font-size:11px">The student will provide written responses to 5 questions about the first
        category. Students will also upload audio recordings of them speaking their responses. After completing
        all 5 questions for that category, the student will be allowed to move onto the next category.
        This process will repeat until the student has completed all 5 categories. After completing the categories,
        the student will have successfully completed all three phases for that country.</p>

    </div>

</div>

quizzes/templates/quizzes/login.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>LOGIN</title>
</head>

<body>
    <div class="mx-auto" style="width: 500px" ;>
        <form action="login_user" method="post" class="form-horizontal">
            {% csrf_token%}
            <div class="col-xs-8 col-xs-offset-4">
                <h2 style="text-align:center;">LOGIN</h2>
            </div>

            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password">
            </div>
            <button type="submit" class="btn btn-primary">LOGIN</button>
            <br />
            <div class="form-group">
                {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{message}}
                </div>
                {% endfor %}
            </div>
        </form>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</body>

</html>

quizzes/templates/quizzes/phase2.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizzes/phase2.js' %}" defer>
    </script>
{% endblock scripts %}


{% block title %}
    {{ obj.name }}
{% endblock title %}

{% block left-btn %}
    <a id="returnButton" class="btn btn-primary btn-sm">
        &#8678; Return to {{ obj.country }}'s Text
    </a>
{% endblock left-btn %}

{% block content %}

    <div>
        <h1 align="center" style="color:MediumSeaGreen">{{ obj.country }}</h1>
        <p align="center" style="font-size:24px">{{ obj.name }} </p>

        <div class="conversation-container"
             id="conversation-container"
             quiz="{{ obj.name }}"
             quiz_country = "{{ obj.country }}"
             historical_image1 = "{{ historical_image1 }}"
             historical_image2 = "{{ historical_image2 }}"
             historical_image3 = "{{ historical_image3 }}"
             image1_desc = "{{ image1_desc }}"
             image2_desc = "{{ image2_desc }}"
             image3_desc = "{{ image3_desc }}"
             video = "{{ video }}">

            <h5> Conversation </h5>
            <p> You are tasked with conversing with a western student on the text you just read. To reference
                this text, press the button in the top left corner.
            </p>

            <div class="slideshow-container" id="slideshow-container" csrf="{% csrf_token %}">
                  <!-- Next and previous buttons -->
                  <a class="prev" id="prev">&#10094;</a>
                  <a class="next" id="next">&#10095;</a>
{#                <div class="mySlides">#}
{#                    <div class="numbertext">1 / 3</div>#}
{##}
{#                    <img class="center" src="https://static.vecteezy.com/system/resources/previews/014/024/805/original/happy-two-cute-kids-little-boys-talking-each-other-with-speech-bubble-vector.jpg" alt="Conversation" style="width:80%;">#}
{#                    <div class="overlay" id="overlay" quiz="{{ obj.name }}"></div>#}
{##}
{#                    <canvas class="canvas" id="canvas"></canvas>#}
{#                    <label for="name">Type Your Response Here:</label>#}
{#                    <input type="text" id="response">#}
{##}
{#                    <form id="quiz-form" class="mt-3 mb-3">#}
{#                        {%  csrf_token %}#}
{#                        <br>#}
{#                        <button class="btn btn-success" id="submitButton" align="center"></button>#}
{#                    </form>#}
{#                </div>#}

            </div>

{#            <!-- The dots/circles -->#}
{#            <div style="text-align:center">#}
{#              <span class="dot" onclick="currentSlide(1)"></span>#}
{#              <span class="dot" onclick="currentSlide(2)"></span>#}
{#              <span class="dot" onclick="currentSlide(3)"></span>#}
{#            </div>#}

        </div>

{#        <div class="quiz-container" id="quiz-container"#}
{#                                    score_needed_to_pass="{{ obj.required_score_to_pass }}">#}
{#            <div id="quiz-container-header"></div>#}
{#            <form id="quiz-form" class="mt-3 mb-3">#}
{#                {%  csrf_token %}#}
{#                <div id="quiz-box"></div>#}
{#                <br>#}
{#                <button type="submit" class="btn btn-success" id="submitButton" align="center"></button>#}
{#            </form>#}
{#            <div id="score-box"></div>#}
{#            <div id="result-box"></div>#}
{#        </div>#}

{% endblock content %}

quizzes/templates/quizzes/quiz.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizzes/quiz.js' %}" defer>
        {#quiz = {{ obj|escapejs }};#}
        {#const historical_image1 = {{ historical_image1 }};#}
        {#const historical_image2 = {{ historical_image2 }};#}
        {#const historical_image3 = {{ historical_image3 }};#}
        {#const image1_desc = {{ image1_desc }};#}
        {#const image2_desc = {{ image2_desc }};#}
        {#const image3_desc = {{ image3_desc }};#}
    </script>
{% endblock scripts %}


{% block title %}
    {{ phase1.name }}
{% endblock title %}

{% block left-btn %}
    <a id="returnButton" class="btn btn-primary btn-sm" countryName="{{ phase1.country }}">&#8678; Return to {{ phase1.country }}'s Progress Page</a>
{% endblock left-btn %}

{% block content %}

    <div>
        <h1 align="center" style="color:MediumSeaGreen">{{ phase1.country }}</h1>
        <p align="center" style="font-size:24px">{{ phase1.name }} </p>

        <div id="multimedia-box"
             quiz="{{ phase1.name }}"
             quiz_country = "{{ phase1.country }}"
             historical_image1 = "{{ historical_image1 }}"
             historical_image2 = "{{ historical_image2 }}"
             historical_image3 = "{{ historical_image3 }}"
             image1_desc = "{{ image1_desc }}"
             image2_desc = "{{ image2_desc }}"
             image3_desc = "{{ image3_desc }}"
             video = "{{ video }}">

{#            <h3><b>{{ obj.country }}'s Historical Places</b></h3>#}
{##}
{#            <div class="row">#}
{#                <div class="column">#}
{#                    <img src={{ historical_image1 }} alt="Historical_Image1" style="width:100%">#}
{#                    <div class="description">{{ image1_desc }}</div>#}
{#                </div>#}
{##}
{#                <div class="column">#}
{#                    <img src={{ historical_image2 }} alt="Historical_Image1" style="width:100%">#}
{#                    <div class="description">{{ image2_desc }}</div>#}
{#                </div>#}
{##}
{#                <div class="column">#}
{#                    <img src={{ historical_image3 }} alt="Historical_Image1" style="width:100%">#}
{#                    <div class="description">{{ image3_desc }}</div>#}
{#                </div>#}
{#            </div>#}

        </div>

        <div class="quiz-container" id="quiz-container"
                                    score_needed_to_pass="{{ phase1.required_score_to_pass }}">
            <div id="quiz-container-header"></div>
{#            <h2>{{ obj.name }}</h2>#}
{#            <br>#}
{#            <p>Score Needed to Pass: {{ obj.required_score_to_pass }}%</p>#}
            <form id="quiz-form" class="mt-3 mb-3">
                {%  csrf_token %}
                <div id="quiz-box"></div>
                <br>
                <button class="btn btn-success" id="submitButton" align="center"></button>
            </form>
            <div id="score-box"></div>
            <div id="result-box"></div>
        </div>

{% endblock content %}