ArabWorldMap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizzes.urls', namespace='quizzes')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

quizzes/urls.py
from django.urls import path
from .views import (
    home,
    register,
    login_user,
    logout_user,
    progress_view,
    quiz_view,
    quiz_data_view,
    submit_quiz_view,
    phase2_view,
    phase2_data_view,
    submit_phase2_view
    )

app_name = 'quizzes'

urlpatterns = [
    path('', home, name='home'),
    path('register', register, name='register'),
    path('login_user', login_user, name='login_user'),
    path('logout_user', logout_user, name='logout_user'),
    path('home', home, name='home'),
    path('<str:countryName>/progress/', progress_view, name='main-view'),
    path('<str:countryName>/progress/<int:pk>/', quiz_view, name='quiz-view'),
    path('<str:countryName>/progress/<int:pk>/submit/', submit_quiz_view, name='submit-view'),
    path('<str:countryName>/progress/<int:pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('<str:countryName>/progress/<int:pk>/phase2/', phase2_view, name='phase2-view'),
    path('<str:countryName>/progress/<int:pk>/phase2/submit/', submit_phase2_view, name='submit-phase2-view'),
    path('<str:countryName>/progress/<int:pk>/phase2/data/', phase2_data_view, name='phase2-data-view'),

]

templates/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en-US">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">


    {% block scripts %}
    {% endblock scripts %}

	<title>{% block title %} {% endblock title %}</title>

    <!-- CSS -->
{#    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>#}
{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>#}
{#    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>#}

{#    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Rubik" rel="stylesheet">#}

{#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">#}
{#    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Rubik" rel="stylesheet">#}


</head>

<body>
    <div class="flex-container">
        <div class="left-btn">
            {% if not request.user.is_active %}
                {# <a href="{% url 'quiz:login' %}" class="btn btn-success mt-1 ml-2"><i class="fa fa-sign-in" aria-hidden="true"></i> Log In</a>#}
                <a href="{% url 'quizzes:login_user' %}">Login</a>
                <a href="{% url 'quizzes:register' %}">Register</a>
            {% else %}
                {% block left-btn %}{% endblock left-btn %}
{#          <a href="{% url 'quiz:logout' %}" class="btn btn-danger mt-1 ml-4">Log Out <i class="fa fa-sign-out" aria-hidden="true"></i></a>#}
            {% endif %}
        </div>
        <div class="right-btn">
            <!-- Trigger/Open The Modal -->
            <button class="btn btn-secondary btn-sm" id="myBtn">Instructions</button>

            <!-- The Modal -->
            {% include 'quizzes/instructions_modal.html' %}
            <script src="{% static 'quizzes/modal_script.js' %}"></script>

    </div>

</div>
{#    <nav class="navbar navbar-expand-md navbar-dark bg-dark">#}
{#        <div class="container">#}
{#            <h1><a href="{% url 'quiz:home' %}" class="navbar-brand">#}
{#            <strong>Quiz-App</strong></a></h1>#}
{#            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>#}
{#            <div class="collapse navbar-collapse justify-content-end " id="navbar">#}
{#                {% if not request.user.is_active %}#}
{#                <a href="{% url 'quiz:login' %}" class="btn btn-success mt-1 ml-2"><i class="fa fa-sign-in" aria-hidden="true"></i> Log In</a>#}
{#                {% else %}#}
{#                <h6 class="text-white mt-2 mr-2">Welcome, {{ request.user.username }}</h6>#}
{#                <h6 class="text-light mt-2 mr-2">|</h6>#}
{#                <h6 class="text-light mt-2 mr-2">|</h6>#}
{#                <a href="{% url 'quiz:logout' %}" class="btn btn-danger mt-1 ml-4">Log Out <i class="fa fa-sign-out" aria-hidden="true"></i></a>#}
{#                {% endif %}#}
{#            </div>#}
{#        </div>#}
{#    </nav>#}

    {% block content %}
    {% endblock content %}

    <!-- jQuery first, then Bootstrap JS -->
{#    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>#}
{#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>#}
{##}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/smooth-scroll/12.1.5/js/smooth-scroll.min.js" integrity="sha256-MMt0/21G3z0Zg4ET1kI3HC9npItDowkitRDVr0FhCxA=" crossorigin="anonymous"></script>#}

{#    <!-- <script src="{% static 'js/main.js' %}"></script>#}
{#    {% block js %}{% endblock js %} -->#}
</body>
</html>